example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
from wishlist.views import xml
from wishlist.views import show_json
from wishlist.views import json_id
from wishlist.views import show_wishlist_ajax
from wishlist.views import wishlist_form

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
    path('xml/', xml, name='xml'),
    path('json/', show_json, name='json'),
    path('json/<int:id>', json_id, name='json_id'),
    path('ajax', show_wishlist_ajax, name='ajax'),
    path('ajax/submit', wishlist_form, name="form")
]

wishlist/urls.py
from unicodedata import name
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import xml
from wishlist.views import show_json
from wishlist.views import json_id 
from wishlist.views import register 
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax
from wishlist.views import wishlist_form

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', xml, name='xml'),
    path('json/', show_json, name='json'),
    path('json/<int:id>', json_id, name='json_id'), 
    path('register/', register, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name="ajax"),
    path('ajax/submit', wishlist_form, name="form")
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from django import forms
from .models import BarangWishlist

class WishListForm(forms.ModelForm):
    class Meta:
        model = BarangWishlist
        fields = ['nama_barang','harga_barang','deskripsi']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from wishlist.forms import WishListForm

@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Felix Tjahyadi',
    'last_login': request.COOKIES['last_login'],
}
    return render(request, "wishlist.html", context)

def show_wishlist_ajax(request):
    context = {
    'nama': 'Felix Tjahyadi',
    }
    return render(request, "wishlist_ajax.html", context)

def wishlist_form(request):
    if request.method == "POST":
        form = WishListForm(request.POST)
        if form.is_valid():
            nama_barang = request.POST.get('nama_barang')
            harga_barang = request.POST.get('harga_barang')
            deskripsi = request.POST.get('deskripsi')
            wishlist = BarangWishlist(nama_barang = nama_barang, harga_barang = harga_barang, deskripsi= deskripsi)
            wishlist.save()
            response = HttpResponseRedirect(reverse("wishlist:wishlist_form")) 
            return response
    else:
        form = WishListForm()
    
    return render(request, 'wishlist_form.html', {'form':form})

def xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def json_id(request, id):
    data_id = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data_id), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) 
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  {% block meta %}
  {% endblock meta %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

wishlist/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, world!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<h5>Nama: </h5>
<p>{{nama}}</p>

<nav class="navbar bg-light">
    <div class="container-fluid">
      <span class="navbar-text navbar-brand mb-0 h1">
        Nama: {{nama}}
        <button type="button" class="btn btn-outline-dark"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
      </span>
    </div>
</nav>

<table class="table table-striped-columns">
    <tr>
    <th class="table-dark">Nama Barang</th>
    <th class="table-dark">Harga Barang</th>
    <th class="table-dark">Deskripsi</th>
    </tr>
    <tbody class="table-group-divider">
    {% for barang in list_barang %}
    <tr>
        <th>
            <p class="fw-normal text-decoration-underline">
            {{barang.nama_barang}}
            </p>
        </th>
        <th>{{barang.harga_barang}}</th>
        <th>
            <p class="fw-normal">
            {{barang.deskripsi}}
            </p>
        </th>
    </tr>
{% endfor %}
</tbody>
</table>

<h5 class="text-uppercase">Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<h5>Nama: </h5>
<p>{{nama}}</p>

<nav class="navbar bg-light">
    <div class="container-fluid">
      <span class="navbar-text navbar-brand mb-0 h1">
        Nama: {{nama}}
        <button type="button" class="btn btn-outline-dark">LoadData</button>
      </span>
    </div>
</nav>

<table class="table table-striped-columns" id="wishlist_table">
    <tr>
    <th class="table-dark">Nama Barang</th>
    <th class="table-dark">Harga Barang</th>
    <th class="table-dark">Deskripsi</th>
    </tr>

</table>

<h5 class="text-uppercase">Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

<script>
  $(document).ready(function(){
    $('button').click(function(){
      $.get("../json/", function(data){
          var wishlist_data = '';
          $.each(data, function(key, value){
              wishlist_data += '<tr>';
              wishlist_data += '<td>'+ value.fields.nama_barang +'</td>';
              wishlist_data += '<td>'+ value.fields.harga_barang +'</td>';
              wishlist_data += '<td>'+ value.fields.deskripsi +'</td>';
              wishlist_data += '</tr>';
          });
          $('#wishlist_table').append(wishlist_data);
      });
    });
  });
</script>

{% endblock content %}

wishlist/templates/wishlist_form.html
{% extends 'base.html' %}

{% block content %}
<h5>Nama: </h5>
<p>Felix Tjahyadi</p>

<nav class="navbar bg-light">
    <div class="container-fluid">
      <span class="navbar-text navbar-brand mb-0 h1">
        <button id="button1" class="btn btn-outline-dark">Load</button>
      </span>
    </div>
</nav>

<table class="table table-striped-columns" id="wishlist_table">
    <tr>
    <th class="table-dark">Nama Barang</th>
    <th class="table-dark">Harga Barang</th>
    <th class="table-dark">Deskripsi</th>
    </tr>

</table>

<h5 class="text-uppercase">Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>

<script>
  $(document).ready(function(){
    $('#button1').click(function(){
      $.get("../json/", function(data){
          var wishlist_data = '';
          $.each(data, function(key, value){
              wishlist_data += '<tr>';
              wishlist_data += '<td>'+ value.fields.nama_barang +'</td>';
              wishlist_data += '<td>'+ value.fields.harga_barang +'</td>';
              wishlist_data += '<td>'+ value.fields.deskripsi +'</td>';
              wishlist_data += '</tr>';
          });
          $('#wishlist_table').append(wishlist_data);
      });
    });
  });
</script>

<form id="form" method="POST" action="" class="">
    {% csrf_token %}
    <div>
        <p>
            Nama Barang:
        </p>
        {{form.nama_barang}}
    </div>
    <div>
        <p>
            Harga Barang:
        </p>
        {{form.harga_barang}}
    </div>
    <div>
        <p>
            Deskripsi Barang:
        </p>
        {{form.deskripsi}}
    </div>
    <input type="submit" name="submit" value="Submit"/>
</form>

<script>
    $(document).ready(function(){
        $("form").on("submit",function(event){
            $.ajax({
                url: '../json/', 
                type : "POST",
                dataType : 'json',
                data : $("form").serialize(),
            })
        });
    });
</script>

{% endblock content %}